language: node_js
node_js:
  - lts/*
script:
  -
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: static
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  target-branch: gh-pages
  keep-history: true
  on:
    branch: master